server.port: 9090
spring:
  profiles:
    active: production
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://125.209.200.185:3306/JunnieJobsTrello
    driverClassName: com.mysql.jdbc.Driver
    username: junnie
    password: ehdwns1q
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  resources:
    chain:
      enabled: true


security:
  oauth2:
    sso:
      login-path: /users/login/facebook
    client:
      clientId: 215599055502858
      clientSecret: 98e9edae2f12a8d42e546319b8a44ee4
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me