server.port: 8080
spring:
  profiles:
    active: server
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://125.209.200.185:3306/TRELLO_ver2
    driverClassName: com.mysql.jdbc.Driver
    username: junnie
    password: ehdwns1q
  resources:
    chain:
      enabled: true

#flyway:
#  enabled: true
#  check-location: true
#  locations: classpath:db/migration
#  baseline-version: 1
#  sql-migration-prefix: V
#  sql-migration-suffix: .sql