drop table board if exists
drop table card if exists
drop table comment if exists
drop table deck if exists
drop table user if exists

create table board (board_id bigint generated by default as identity, board_name varchar(50) not null, primary key (board_id))
create table card (card_id bigint generated by default as identity, description varchar(3000), title varchar(150) not null, deck_deckId bigint not null, primary key (card_id))
create table comment (comment_id bigint generated by default as identity, contents varchar(1000) not null, time_stamp varchar(255), username varchar(255) not null, card_cardId bigint, primary key (comment_id))
create table deck (deck_id bigint generated by default as identity, deck_name varchar(50) not null, board_boardId bigint not null, primary key (deck_id))
create table user (id bigint generated by default as identity, email varchar(255), password varchar(255), username varchar(255), primary key (id))
alter table card add constraint fk_deck_id foreign key (deck_deckId) references deck
alter table comment add constraint fk_comment_parent_id foreign key (card_cardId) references card
alter table deck add constraint FK_qedr66riq985lq9gs9y10o419 foreign key (board_boardId) references board